# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3f980fa1417d9cfcbd7c3fbb6406b1d02e753c16fea740b76e6ddd3dd7eab4a64e369cdacf58e55c4867fc36af14f5dbd53b10179cb62e7b35cd548e457b3ee3

test:
  secret_key_base: 07a4e2c3c25aa32829b0521e3c2fa696b8d35bb717b606fc25b720f22acbd63e503f6961a18abd2d7635efa767310442561a47367828dc9dad9b012d384a3943

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
